// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDFQPK8EmkIBqKElL1xHEF6gQ2EUni0AA',
    appId: '1:552787085648:web:48cb2f33356061d5c40455',
    messagingSenderId: '552787085648',
    projectId: 'afosen-b3b15',
    authDomain: 'afosen-b3b15.firebaseapp.com',
    storageBucket: 'afosen-b3b15.appspot.com',
    measurementId: 'G-J7WX3719LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRi6jyzWwvav2_dflXfcviRA9iWCLFZo',
    appId: '1:552787085648:android:85c7b54ef1453b59c40455',
    messagingSenderId: '552787085648',
    projectId: 'afosen-b3b15',
    storageBucket: 'afosen-b3b15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnBnVPtjUJ59kf7wdRayvvVKOoIGo749c',
    appId: '1:552787085648:ios:d205604ff8e93ee4c40455',
    messagingSenderId: '552787085648',
    projectId: 'afosen-b3b15',
    storageBucket: 'afosen-b3b15.appspot.com',
    iosBundleId: 'com.example.afsoen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnBnVPtjUJ59kf7wdRayvvVKOoIGo749c',
    appId: '1:552787085648:ios:0dd8bbecb12e4ba1c40455',
    messagingSenderId: '552787085648',
    projectId: 'afosen-b3b15',
    storageBucket: 'afosen-b3b15.appspot.com',
    iosBundleId: 'com.example.afsoen.RunnerTests',
  );
}
